version: '3.8'

services:
  postgres:
    image: postgres:18.1
    container_name: neocircuit-postgres
    restart: always
    environment:
      POSTGRES_USER: neocircuit_user
      POSTGRES_PASSWORD: neocircuit_password
      POSTGRES_DB: neocircuit_lab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  n8n:
    image: n8nio/n8n
    container_name: neocircuit-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Asuncion
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=neocircuit_lab
      - DB_POSTGRESDB_USER=neocircuit_user
      - DB_POSTGRESDB_PASSWORD=neocircuit_password
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data:
